export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

import Button from '@mui/material/Button';
import BackButton from '@/components/ui/BackButton';
import Link from 'next/link';

export default async function RegisterTemplate({ children }) {

    return (
        <div className="auth_layout main_font">

                <div className="auth_content row h-100">

                    {/* less than 992px hide this col */}
                    <div className={`col-lg-5 col-12 h-100 login_left_col d-none d-lg-block`}>

                        <div className="auth_left">
                            <div className="auth_left_top">
                            <BackButton className="d-none d-lg-inline-flex" />
                            {/* <Button className='main_font auth_back_btn' startIcon={<i className="fa-solid fa-arrow-left"></i>} variant="contained" >عودة</Button> */}
                            </div>
                            <div className="auth_left_center me-2" dir='rtl'>
                                <h1 className='auth_title mb-4 '> مرحباً بعودتك !</h1>
                                <p className='auth_subtitle mb-4 '> لتبقي علي تواصل معنا من فضلك قم بالتسجيل الأن.</p>
                                <Link href={"/login"}>
                                    <Button className='main_font auth_center_btn'   sx={{
                                        '& .MuiButton-startIcon': {
                                                marginLeft: '10px', 
                                            },
                                        }} startIcon={<i className="fa-solid fa-arrow-right"></i>} variant="contained">
                                        
                                        تسجيل الدخول
                                    
                                    </Button>
                                </Link>

                            </div>
                        </div>
                    </div>



                    <div className={`col-lg-7 col-12 auth_right_col`}>

                        <div className="auth_right ">
                            {/* more than 992 hide this element */}
                                <BackButton className="d-inline-flex d-lg-none" />
                                {children}
                        </div>
                    </div>

            </div>
        </div>
    );
}
