import "../assets/styles/style.css"
// Importing FontAwesome
import '@fortawesome/fontawesome-free/css/all.min.css';
// Importing Bootstrap CSS + JS
import BootstrapClient from "@/utils/BootstrapImporting";

import { Tajawal , Mr_Dafoe } from "next/font/google";

const tajawal = Tajawal({
  weight: ["200", "400", "700"],
  subsets: ["arabic"],
});

const mrDafoe = Mr_Dafoe({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${tajawal.className} ${mrDafoe.className}`}>
        <BootstrapClient/>

        {children}

      </body>
    </html>
  );
}
